# -*- coding: utf-8 -*-
"""machine_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IQxiRFTJtgR1gFE8-ekSnAa1EaHOirWI
"""

import numpy as np
import pandas as pd

data = np.array([15, 16, 16, 17, 18, 18, 18, 19, 20])
print("میانگین : ", np.mean(data))
print("واریانس : ", np.var(data))
print("انحراف معیار :", np.std(data))

df = pd.DataFrame({
    "نام بیمارن":['Sobhan', 'Ali', 'Mohammad', 'Reza', 'Maryam'],
    "دما":[34.2, 23.2, 12.0, 11.3, 34.5]
})
df

df = pd.DataFrame({
    "نام بیماران ": ["سبحان", "علی", "مریم"],
    "فشار خون" : [80.0, 100.0, 139.0]
})
df